name: golf_rangefinder
description: "A Flutter-based golf rangefinder app using Mapbox."
publish_to: 'none' # This prevents accidental publishing to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.0
  mapbox_gl: ^0.15.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # Uncomment and update if you add custom assets
  # assets:
  #   - assets/images/

  # Uncomment and update if you add custom fonts
  # fonts:
  #   - family: YourFontFamily
  #     fonts:
  #       - asset: fonts/YourFontFile.ttf
