# Uncomment this line to define a global platform for your project
platform :ios, '12.0'

# Add your Mapbox token here
ENV['MAPBOX_DOWNLOADS_TOKEN'] ||= 'sk.eyJ1Ijoicmlja2gybmQiLCJhIjoiY205MGNwd2J6MGY0ajJucHl6bjU2Z3hjeSJ9.A6c-vhIK_yYWkdwg3uw6dA'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

# Include the Flutter pod helper to define flutter_install_all_ios_pods and flutter_additional_ios_build_settings.
require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper.rb'))

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

# Prevent CocoaPods from creating a second Xcode workspace (we already have Runner.xcworkspace)
workspace 'Runner.xcworkspace'

target 'Runner' do
  use_modular_headers!
  
  # This installs all Flutter dependencies and plugins.
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
