platform :ios, '12.0'
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

source 'https://cdn.cocoapods.org/'
source 'https://github.com/CocoaPods/Specs.git'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Flutter Engine Pods
  pod 'Flutter', :path => '.flutter-plugins/flutter'

  # Plugin pods (adjust as needed)
  pod 'mapbox-ios-sdk', '6.4.1' # or use your custom setup if required

  # Add any other plugin pods manually here based on pubspec.yaml

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
    end
  end
end