name: iOS Build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    env:
      FLUTTER_VERSION: "3.29.2"
      MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: stable
          cache: true

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Create .netrc for Mapbox (CocoaPods auth)
        run: |
          echo "machine api.mapbox.com" >> ~/.netrc
          echo "login mapbox" >> ~/.netrc
          echo "password $MAPBOX_ACCESS_TOKEN" >> ~/.netrc
          chmod 600 ~/.netrc

      - name: Fix CocoaPods repo (handle EOF error)
        run: |
          pod repo remove trunk || true
          pod setup

      - name: Install CocoaPods
        run: |
          cd ios
          pod install

      - name: Build iOS app
        run: flutter build ios --release --no-codesign