name: Build iOS Flutter App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter 3.29.2
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
          channel: stable
          cache: true

      - name: Confirm Flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

- name: Set up .netrc for Mapbox SDK
  run: |
    echo "machine api.mapbox.com" > ~/.netrc
    echo "login mapbox" >> ~/.netrc
    echo "password ${{ secrets.MAPBOX_DOWNLOADS_TOKEN }}" >> ~/.netrc
    chmod 600 ~/.netrc

      - name: Install CocoaPods
        working-directory: ios
        run: pod install

      - name: Build iOS (release, no codesign)
        run: flutter build ios --release --no-codesi