name: iOS Build

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build iOS App
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'

      - name: Install Flutter Dependencies
        run: flutter pub get

      - name: Set .netrc permissions to avoid CocoaPods error
        run: chmod 600 ~/.netrc || true

      - name: Install CocoaPods
        run: |
          cd ios
          pod install

      - name: Build iOS
        run: flutter build ios --release --no-codesign