name: Build iOS Flutter App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
on:
  workflow_dispatch:  # <-- allows manual trigger
  push:
    branches:
      - master
jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.5'  # Replace with your Flutter version
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Enable iOS
        run: flutter config --enable-ios

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          cd ios
          pod install
          cd ..

      - name: Build iOS
        run: flutter build ios --release --no-codesign

      - name: Archive build
        uses: actions/upload-artifact@v3
        with:
          name: ios-release-build
          path: build/ios/iphoneos/Runner.app