name: iOS Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-ios:
    name: Build iOS App
    runs-on: macos-14

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Set up .netrc for Mapbox (auth)
        run: |
          echo "machine api.mapbox.com" >> ~/.netrc
          echo "login mapbox" >> ~/.netrc
          echo "password ${{ secrets.MAPBOX_ACCESS_TOKEN }}" >> ~/.netrc
          chmod 600 ~/.netrc

      - name: Install CocoaPods
        run: |
          cd ios
          pod install

      - name: Build iOS App
        run: flutter build ios --no-codesign